# Default values for devel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameSpace: mg

replicaCount: 1

image:
  repository: tuner/app
  mysqlitory: tuner/mysql
  tag: latest
  pullPolicy: Always


mysql:
  type: NodePort
  port: 3306
  nodePort: 31306

server:
  type: NodePort
  port: 4234
  nodePort: 31423
