# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameSpace: development

replicaCount: 1

image:
  repository: tuner/jenkins
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 31367
