# Default values for git.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameSpace: development
genericName: "git"
nameOverride: "git"
fullnameOverride: "git"

replicaCount: 1

image:
  repository: tuner/git
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9418

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.kube
      paths: []
