# Default values for git.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameSpace: development

replicaCount: 1

image:
  repository: tuner/git
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9418
