apiVersion: v1
kind: Pod
metadata:
  name: {{ include "devel.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    service: devel
{{ include "devel.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  volumes:
  - name: devel-vol
    persistentVolumeClaim:
      claimName: devel-pvc
  containers:
  - name: {{ include "devel.fullname" . }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: [ '/bin/bash', '-c', '--' ]
    args:  [ 'while true; do sleep 30; done;' ]
    volumeMounts:
    - name: devel-vol
      mountPath: /data
  restartPolicy: Never
