apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}-client
  namespace: {{ .Values.nameSpace }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}-client
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}-client
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-{{ include "app.name" . }}-client
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: [ "/bin/bash", "-c", "--" ]
        args:  [ "cd /data && tar xvzf --skip-old-files /tmp/user_home.tgz ; echo '#!/bin/bash' > /data/start_container.sh ; echo 'while true; do sleep 30; done;' >> /data/start_container.sh ; chmod u+x /data/start_container.sh ; chown -R app /data" ]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: {{ include "app.name" . }}-client-vol
          mountPath: /data
      containers:
        - name: {{ include "app.name" . }}-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "app.name" . }}-client-vol
      volumes:
        - name: {{ include "app.name" . }}-client-vol
          persistentVolumeClaim:
            claimName: {{ include "app.name" . }}-client-pvc


