---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-handler
  namespace: {{ .Values.nameSpace }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.handler.type }}
  ports:
    - port: {{ .Values.handler.port }}
      nodePort: {{ .Values.handler.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}-handler
    app.kubernetes.io/instance: {{ .Release.Name }}

