---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-mysql
  namespace: {{ .Values.nameSpace }}
  labels:
    service: {{ include "app.name" . }}
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.mysql.type }}
  ports:
    - port: {{ .Values.mysql.port }}
      nodePort: {{ .Values.mysql.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}

