---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "app.name" . }}-mysql
  namespace: {{ .Values.nameSpace }}
  labels:
    service: {{ include "app.name" . }}-mysql
{{ include "app.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
  - name: init-{{ include "app.name" . }}-mysql
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: [ "/bin/bash", "-c", "--" ]
    args:  [ "touch /data/test && chown -R app /data" ]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: {{ include "app.name" . }}-mysql-vol
      mountPath: /data
  containers:
  - name: {{ include "app.name" . }}-mysql
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: [ "/bin/bash", "-c", "--" ]
    args:  [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: {{ include "app.name" . }}-mysql-vol
      mountPath: /data
  volumes:
  - name: {{ include "app.name" . }}-mysql-vol
    persistentVolumeClaim:
      claimName: {{ include "app.name" . }}-mysql-pvc
  restartPolicy: Never
