---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.name" . }}-mysql-pv
  namespace: {{ .Values.nameSpace }}
  labels:
    service: {{ include "app.name" . }}-mysql
    type: local
{{ include "app.labels" . | indent 4 }}
spec:
  storageClassName: tuni.thek
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/volumes/{{ include "app.name" . }}-mysql
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Values.nameSpace }}
    name: {{ include "app.name" . }}-mysql-pvc
