---

apiVersion: v1
kind: Pod
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    service: {{ include "app.name" . }}
{{ include "app.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
  - name: init-devel
    image: tuner/gentoo:latest
    command:
    - sh
    - '-c'
    - 'touch /data/test && chown 1000 /data'
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: {{ include "app.name" . }}-vol
      mountPath: /data
  containers:
  - name: {{ include "app.name" . }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: [ "/bin/bash", "-c", "--" ]
    args:  [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: {{ include "app.name" . }}-vol
      mountPath: /data
  volumes:
  - name: {{ include "app.name" . }}-vol
    persistentVolumeClaim:
      claimName: {{ include "app.name" . }}-pvc
  restartPolicy: Never
