---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "app.name" . }}-server
  namespace: {{ .Values.nameSpace }}
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
  - name: {{ include "app.name" . }}-server
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: [ "/bin/bash", "-c", "--" ]
    args:  [ "while true; do sleep 30; done;" ]
  restartPolicy: Never
