apiVersion: v1
kind: Pod
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    service: {{ include "app.name" . }}
{{ include "app.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  service: {{ include "app.name" . }}
  volumes:
  - name: {{ include "app.name" . }}-vol
    persistentVolumeClaim:
      claimName: {{ include "app.name" . }}-pvc
  containers:
  - name: {{ include "app.name" . }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: ['tail']
    args:  ['-f', '/dev/null']
    volumeMounts:
    - name: {{ include "app.name" . }}-vol
      mountPath: /data
  restartPolicy: Never
