---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
  namespace: {{ .Values.nameSpace }}
spec:
  storageClassName: tuni.thek
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
