# Gentoo Base Test Container
##
## Run:
##    ./manage_docker.sh test gentoo --build

## Include the portage tree
FROM gentoo/portage:latest as portage

## Use Gentoo stage3 as base image
FROM gentoo/stage3-amd64:latest

## Copy the portage tree into the current stage
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

## Install some essentials
RUN echo 'alias ll="ls -lah --color=auto"' >> /etc/bash/bashrc && \
    emerge -D app-editors/vim
