apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    service: jenkins
{{ include "jenkins.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
