apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-{{ include "app.name" . }}
        image: tuner/gentoo-skel:latest
        command:
        - sh
        - '-c'
        - 'touch /data/test && chown 1000 /data'
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: {{ include "app.name" . }}-vol
          mountPath: /data
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "-c", "--" ]
          args:  [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - mountPath: /data
              name: {{ include "app.name" . }}-vol
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 360
            periodSeconds: 360
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 360
            periodSeconds: 360
      volumes:
        - name: {{ include "app.name" . }}-vol
          persistentVolumeClaim:
            claimName: {{ include "app.name" . }}-pvc
