---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: {{ .Values.nameSpace }}
  labels:
{{ include "jenkins.labels" . | indent 4 }}
spec:
  storageClassName: tuni.thek
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
